src/Entity/Inscription.php
<?php

namespace App\Entity;

use App\Repository\InscriptionRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: InscriptionRepository::class)]
class Inscription
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $prenoms = null;

    #[ORM\Column(length: 255)]
    private ?string $telephone = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column]
    private ?\DateTime $date_inscription = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenoms(): ?string
    {
        return $this->prenoms;
    }

    public function setPrenoms(string $prenoms): self
    {
        $this->prenoms = $prenoms;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getDateInscription(): \DateTime
    {
        return $this->date_inscription;
    }

    public function setDateInscription(\DateTime $date_inscription): self
    {
        $this->date_inscription = $date_inscription;

        return $this;
    }
}

src/Form/InscriptionType.php
<?php

namespace App\Form;

use App\Entity\Inscription;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class InscriptionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom', TextType::class, [
                'label' => 'Nom',
                'attr' => [
                    'placeholder' => 'Entrez votre nom',
                ]
            ])
            ->add('prenoms', TextType::class, [
                'label' => 'Prénoms',
                'attr' => [
                    'placeholder' => 'Entrez vos prénoms'
                ]
            ])
            ->add('telephone', TextType::class, [
                'label' => 'Téléphone',
                'attr' => [
                    'placeholder' => 'Entrez votre numéro de téléphone'
                ]
            ])
            ->add('email', EmailType::class, [
                'label' => 'Email',
                'attr' => [
                    'placeholder' => 'Entrez votre adresse email'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Inscription::class,
        ]);
    }
}

src/Controller/InscriptionController.php
<?php

namespace App\Controller;

use App\Entity\Inscription;
use App\Form\InscriptionType;
use App\Repository\InscriptionRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class InscriptionController extends AbstractController
{
    #[Route('/', name: 'app_inscription_index', methods: ['GET'])]
    public function index(InscriptionRepository $inscriptionRepository, Request $request, PaginatorInterface $paginator): Response
    {
        $inscriptions = $paginator->paginate(
            $inscriptionRepository->findBy([], ['date_inscription' => 'DESC']),
            $request->query->getInt('page', 1),
            20
        );
        return $this->render('inscription/index.html.twig', [
            'inscriptions' => $inscriptions,
        ]);
    }

    #[Route('/nouvelle-inscription', name: 'app_inscription_new', methods: ['GET', 'POST'])]
    public function new(Request $request, InscriptionRepository $inscriptionRepository): Response
    {
        $inscription = new Inscription();
        $form = $this->createForm(InscriptionType::class, $inscription);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $inscription->setDateInscription(new \DateTime());
            $inscriptionRepository->save($inscription, true);

            return $this->redirectToRoute('app_inscription_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('inscription/new.html.twig', [
            'inscription' => $inscription,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/edition', name: 'app_inscription_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Inscription $inscription, InscriptionRepository $inscriptionRepository): Response
    {
        $form = $this->createForm(InscriptionType::class, $inscription);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $inscriptionRepository->save($inscription, true);

            return $this->redirectToRoute('app_inscription_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('inscription/edit.html.twig', [
            'inscription' => $inscription,
            'form' => $form,
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="{{ asset('images/logo.png') }}">
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/inscription/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <div class="d-flex mt-4">
        <button class="btn btn-sm btn-primary me-4">{{ button_label|default('Enregistrer') }}</button>
        <a class="btn btn-sm btn-secondary" href="{{ path('app_inscription_index') }}">Retour au listing</a>
    </div>
{{ form_end(form) }}

templates/inscription/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier une inscription{% endblock %}

{% block body %}
    <div class="container mt-4">
        <div class="d-flex mb-4">
            <img src="{{ asset('images/banner.jpeg') }}" alt="image_simplon" height="80">
            <h1 class="mt-5 ms-5">Modifier les informations d'une inscription</h1>
        </div>
        <div class="row">
            <div class="row">
                <div class="col-6">
                    {{ include('inscription/_form.html.twig', {'button_label': 'Modifier'}) }}
                </div>
                <div class="col-6">
                    <img src="{{ asset('images/personnes.jpg') }}" alt="image_simplon" height="350">
                </div>
        </div>
    </div>
{% endblock %}

templates/inscription/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des inscrits{% endblock %}

{% block body %}
    <div class="container mt-4">
        <div class="d-flex mb-4">
            <img src="{{ asset('images/banner.jpeg') }}" alt="image_simplon" height="80">
            <h1 class="mt-5 ms-5">Liste de présence</h1>
        </div>

        <a class="mb-4 btn btn-sm btn-secondary" href="{{ path('app_inscription_new') }}">Faire une inscription</a>

        <table class="table table-responsive table-striped table-bordered text-center">
            <thead>
            <tr>
                <th>#</th>
                <th>Nom</th>
                <th>Prénoms</th>
                <th>Numéro de téléphone</th>
                <th>Email</th>
                <th>Date d'inscription</th>
                <th>action</th>
            </tr>
            </thead>
            <tbody>
            {% for inscription in inscriptions %}
                <tr>
                    <td>{{ loop.index }}</td>
                    <td>{{ inscription.nom }}</td>
                    <td>{{ inscription.prenoms }}</td>
                    <td>{{ inscription.telephone }}</td>
                    <td>{{ inscription.email }}</td>
                    <td>{{ inscription.dateInscription ? inscription.dateInscription|date('d-m-Y H:i:s') : '' }}</td>
                    <td>
                        <a class="btn btn-sm btn-primary" href="{{ path('app_inscription_edit', {'id': inscription.id}) }}">Modifier</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="7">Aucun enregistrement</td>
                </tr>
            {% endfor %}
            </tbody>

        </table>
        <div class="mt-4 mb-3">
            {{ knp_pagination_render(inscriptions, '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig') }}
            <a class="me-4 btn btn-sm btn-secondary" href="{{ path('app_inscription_new') }}">Faire une inscription</a>
        </div>
    </div>
{% endblock %}

templates/inscription/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle inscription{% endblock %}

{% block body %}
    <div class="container mt-4">
        <div class="d-flex mb-4">
            <img src="{{ asset('images/banner.jpeg') }}" alt="image_simplon" height="80">
            <h1 class="mt-5 text-uppercase ms-5">Nouvelle inscription</h1>
        </div>
        <div class="row">
            <div class="col-6">
                {{ include('inscription/_form.html.twig') }}
            </div>
            <div class="col-6">
                <img src="{{ asset('images/personnes.jpg') }}" alt="image_simplon" height="350">
            </div>
        </div>
    </div>
{% endblock %}